### ISSUE TITLE
Place Portal Page not working for newly public dataset

### ISSUE THREAD

**Issue by alexstrb** [WorldHistoricalGazetteer/whg3#403]
Upon request from the creator, I made the dataset [Father Monserrate's Travels in Mughal India](https://whgazetteer.org/datasets/1575/places) public. When doing a spot check test of the places using the search function, I get a hit for the place but when I try to click on "place details" I get an error "Sorry, the requested page does not exist!" I tested this with ~10 places and got the same result each time.

**Comment by docuracy** [comment]
No places were appearing on the map - I've fixed it, but need to make another Issue to make sure it doesn't happen again. If it does (for my future reference) it's necessary follow the instructions for refreshing mapdata [here](https://github.com/WorldHistoricalGazetteer/whg3/blob/staging/developer/deployment-protocol.md#regenerate-map-data).

**Comment by alexstrb** [comment]
Thanks, Stephen. I am getting the attached error still but perhaps that's because you're still working through it.

Ali

________________________________

**Comment by docuracy** [comment]
I've fixed the problem with the search page error, and another which then became apparent whereby unaccessioned places cannot have portal pages and so are linked instead to the place detail page.

**Comment by alexstrb** [comment]
Awesome, thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
